name: Build
on: [push]

jobs:
  Windows:
    name: windows-${{ matrix.config }}
    runs-on: windows-2025
    strategy:
      fail-fast: false
      matrix:
        config: [release, debug]

    steps:
    - uses: actions/checkout@v4

    - name: submodules
      shell: bash
      run: |
        ./submodules.sh

    - name: build
      shell: bash
      run: |
        root_dir=`pwd`
        mkdir build
        cd build
        cmake -Tclangcl ..
        cmake --build . --config ${{ matrix.config }} ${paralel}
        cmake --install . --config ${{ matrix.config }} --prefix "${root_dir}/install"

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: dawn-windows-${{ matrix.config }}
        path: install

  Linux:
    name: linux
    runs-on: ubuntu-latest
    env:
      CC: clang
      CXX: clang++

    steps:
    - uses: actions/checkout@v4

    - name: submodules
      shell: bash
      run: |
        ./submodules.sh

    - name: build
      shell: bash
      run: |
        root_dir=`pwd`
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=release ..
        cmake --build . ${paralel}
        cmake --install . --prefix "${root_dir}/install"

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: dawn-linux
        path: install

  Package:
    runs-on: ubuntu-latest
    needs: [Windows, Linux]
    steps:
    - uses: actions/checkout@v4

    - name: download
      uses: actions/download-artifact@v4
      with:
        path: ./
        merge-multiple: true

    - name: package
      run: |
        mkdir -p install/dawn
        cd install/dawn
        cp ../../DawnConfig.cmake .
        cp -r ../../include .
        mkdir lib
        cp ../../lib/*.a lib
        cp ../../lib/*.lib lib
        cd ..
        zip -r ../dawn.zip dawn

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: latest
        name: "Latest build"
        files: dawn.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
