name: Build
on: [push]

jobs:
  Build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2025, ubuntu-24.04]

    steps:
    - uses: actions/checkout@v4

    - name: submodules
      shell: bash
      run: |
        git submodule update --init --recursive --jobs 8 || echo "some submodules may have failed and it may be ok"

    - name: build
      shell: bash
      run: |
        ./run.sh

    - name: upload
      uses: actions/upload-artifact@v4
      with:
        name: dawn-${{ runner.os }}
        path: install_*

  Package:
    runs-on: ubuntu-latest
    needs: Build
    steps:
    - name: download
      uses: actions/download-artifact@v4
      with:
        path: ./

    - name: package
      run: |
        ./package.sh

    - name: release
      uses: softprops/action-gh-release@v1
      with:
        files: dawn.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
